spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/borders
    username: borders
    password: borders

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

