spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:borders
    username: borders
    password:

  sql:
    init:
      platform: h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true




